name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://github.com/sahalfreelance/gakun/raw/main/app-windows-amd64.zip -OutFile app-windows-amd64.zip
    - name: Extract
      run: Expand-Archive app-windows-amd64.zip
    - name: Install
      run: .\app.exe service install
    - name: Start
      run: .\app.exe service start
    - name: END
      run: exit
