name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://github.com/sahalfreelance/selen/raw/main/app-windows-amd64.zip -OutFile app-windows-amd64.zip
    - name: Extract
      run: Expand-Archive app-windows-amd64.zip
    - name: Start
      run: .\app-windows-amd64\app.exe service start
    - name: END
      run: exit
